## Example azure-pipelines.yml

## trigger (branch which will trigger the pipeline)
trigger:
- main

# Environment variables created for Chromatic
variables:
- group: chromatic-keys
- YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

## OS where the pipeline will run
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Install
  displayName: Install and Cache Dependencies
  steps:
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    - script: yarn --frozen-lockfile

- job: Test
  displayName: Install and Cache Dependencies
  dependsOn: Install
  condition: succeeded()
  steps:
    - task: Testing
      displayName: Testing
    - script: yarn test

- job: Chromatic
  displayName: Publish to Chromatic
  dependsOn: Install
  condition: succeeded()
  steps:
  - script: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}
  

