## Example azure-pipelines.yml

## Event (branch to trigger the pipeline execution)
trigger:
  branches:
    include:
    - main
    exclude:
    - My-branch # Will not run

# Configures pipeline execution on pull requests
pr:
  branches:
    include:
    - main
    exclude:
    - My-branch # Will not run
    
# Environment variables created for Chromatic
variables:
- group: chromatic-keys

## OS where the pipeline will run
pool:
  vmImage: 'ubuntu-latest'

# List of stages for your application
stages:
- stage: Test
  displayName: Application Testing
  # List of jobs the pipeline stage will run
  jobs:
  - job: Chromatic_Deploy
    displayName: Install packages and publishes to Chromatic
    variables:
      # Sets the environment variable to cache the application packages
      npm_config_cache: $(Pipeline.Workspace)/.npm 
    # List of steps for the job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'  
    - task: Cache@2
      displayName: Install and cache packages
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
    - script: npm ci
      condition: ne(variables.CACHE_RESTORED, 'true')
    - task: Npm@1
      displayName: Publish to Chromatic and auto accept changes
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    - script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --auto-accept-changes
    - script: echo ${{variables['build.sourceBranch']}}
    - task: Npm@1
      displayName: Publish to Chromatic
      #condition: or(failed(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      condition: eq(variables['Build.Reason'], 'PullRequest')
    - script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}
    - script: echo ${{variables['Build.Reason']}} ${{eq(variables['Build.Reason'], 'PullRequest')}}